//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yapped_Rune_Bear.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.4.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ExampleMod")]
        public string ProjectName {
            get {
                return ((string)(this["ProjectName"]));
            }
            set {
                this["ProjectName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point WindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["WindowLocation"]));
            }
            set {
                this["WindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("776, 584")]
        public global::System.Drawing.Size WindowSize {
            get {
                return ((global::System.Drawing.Size)(this["WindowSize"]));
            }
            set {
                this["WindowSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WindowMaximized {
            get {
                return ((bool)(this["WindowMaximized"]));
            }
            set {
                this["WindowMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Program Files (x86)\\\\Steam\\\\steamapps\\\\common\\\\ELDEN RING\\\\Game\\\\regulation.b" +
            "in")]
        public string RegulationPath {
            get {
                return ((string)(this["RegulationPath"]));
            }
            set {
                this["RegulationPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int SplitterDistance1 {
            get {
                return ((int)(this["SplitterDistance1"]));
            }
            set {
                this["SplitterDistance1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedParam {
            get {
                return ((int)(this["SelectedParam"]));
            }
            set {
                this["SelectedParam"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedRow {
            get {
                return ((int)(this["SelectedRow"]));
            }
            set {
                this["SelectedRow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SelectedField {
            get {
                return ((int)(this["SelectedField"]));
            }
            set {
                this["SelectedField"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VerifyRowDeletion {
            get {
                return ((bool)(this["VerifyRowDeletion"]));
            }
            set {
                this["VerifyRowDeletion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeHeaderInCSV {
            get {
                return ((bool)(this["IncludeHeaderInCSV"]));
            }
            set {
                this["IncludeHeaderInCSV"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludePaddingInExport
        {
            get
            {
                return ((bool)(this["IncludePaddingInExport"]));
            }
            set
            {
                this["IncludePaddingInExport"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool IncludeRowNameInCSV {
            get {
                return ((bool)(this["IncludeRowNameInCSV"]));
            }
            set {
                this["IncludeRowNameInCSV"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(";")]
        public string ExportDelimiter {
            get {
                return ((string)(this["ExportDelimiter"]));
            }
            set {
                this["ExportDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("249")]
        public int SplitterDistance2 {
            get {
                return ((int)(this["SplitterDistance2"]));
            }
            set {
                this["SplitterDistance2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DGVIndices {
            get {
                return ((string)(this["DGVIndices"]));
            }
            set {
                this["DGVIndices"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowCommonParamsOnly {
            get {
                return ((bool)(this["ShowCommonParamsOnly"]));
            }
            set {
                this["ShowCommonParamsOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ChangedCommonParamView {
            get {
                return ((bool)(this["ChangedCommonParamView"]));
            }
            set {
                this["ChangedCommonParamView"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ParamsToIgnoreDuringSave {
            get {
                return ((string)(this["ParamsToIgnoreDuringSave"]));
            }
            set {
                this["ParamsToIgnoreDuringSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EldenRing")]
        public string GameType {
            get {
                return ((string)(this["GameType"]));
            }
            set {
                this["GameType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowConfirmationMessages {
            get {
                return ((bool)(this["ShowConfirmationMessages"]));
            }
            set {
                this["ShowConfirmationMessages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseTextEditor {
            get {
                return ((bool)(this["UseTextEditor"]));
            }
            set {
                this["UseTextEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FieldExporter_RetainFieldText {
            get {
                return ((bool)(this["FieldExporter_RetainFieldText"]));
            }
            set {
                this["FieldExporter_RetainFieldText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldExporter_FieldMatch {
            get {
                return ((string)(this["FieldExporter_FieldMatch"]));
            }
            set {
                this["FieldExporter_FieldMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldExporter_FieldMinimum {
            get {
                return ((string)(this["FieldExporter_FieldMinimum"]));
            }
            set {
                this["FieldExporter_FieldMinimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldExporter_FieldMaximum {
            get {
                return ((string)(this["FieldExporter_FieldMaximum"]));
            }
            set {
                this["FieldExporter_FieldMaximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldExporter_FieldExclusion {
            get {
                return ((string)(this["FieldExporter_FieldExclusion"]));
            }
            set {
                this["FieldExporter_FieldExclusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldExporter_FieldInclusion {
            get {
                return ((string)(this["FieldExporter_FieldInclusion"]));
            }
            set {
                this["FieldExporter_FieldInclusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TextEditorPath {
            get {
                return ((string)(this["TextEditorPath"]));
            }
            set {
                this["TextEditorPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SecondaryFilePath {
            get {
                return ((string)(this["SecondaryFilePath"]));
            }
            set {
                this["SecondaryFilePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ParamDifferenceMode {
            get {
                return ((bool)(this["ParamDifferenceMode"]));
            }
            set {
                this["ParamDifferenceMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldAdjuster_FieldMatch {
            get {
                return ((string)(this["FieldAdjuster_FieldMatch"]));
            }
            set {
                this["FieldAdjuster_FieldMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldAdjuster_RowRange {
            get {
                return ((string)(this["FieldAdjuster_RowRange"]));
            }
            set {
                this["FieldAdjuster_RowRange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldAdjuster_RowPartialMatch {
            get {
                return ((string)(this["FieldAdjuster_RowPartialMatch"]));
            }
            set {
                this["FieldAdjuster_RowPartialMatch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldAdjuster_FieldMinimum {
            get {
                return ((string)(this["FieldAdjuster_FieldMinimum"]));
            }
            set {
                this["FieldAdjuster_FieldMinimum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldAdjuster_FieldMaximum {
            get {
                return ((string)(this["FieldAdjuster_FieldMaximum"]));
            }
            set {
                this["FieldAdjuster_FieldMaximum"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldAdjuster_FieldExclusion {
            get {
                return ((string)(this["FieldAdjuster_FieldExclusion"]));
            }
            set {
                this["FieldAdjuster_FieldExclusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldAdjuster_FieldInclusion {
            get {
                return ((string)(this["FieldAdjuster_FieldInclusion"]));
            }
            set {
                this["FieldAdjuster_FieldInclusion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldAdjuster_Formula {
            get {
                return ((string)(this["FieldAdjuster_Formula"]));
            }
            set {
                this["FieldAdjuster_Formula"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldAdjuster_ValueMin {
            get {
                return ((string)(this["FieldAdjuster_ValueMin"]));
            }
            set {
                this["FieldAdjuster_ValueMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FieldAdjuster_ValueMax {
            get {
                return ((string)(this["FieldAdjuster_ValueMax"]));
            }
            set {
                this["FieldAdjuster_ValueMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FieldAdjuster_RetainFieldText {
            get {
                return ((bool)(this["FieldAdjuster_RetainFieldText"]));
            }
            set {
                this["FieldAdjuster_RetainFieldText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Settings_LogParamSize {
            get {
                return ((bool)(this["Settings_LogParamSize"]));
            }
            set {
                this["Settings_LogParamSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveWithoutEncryption {
            get {
                return ((bool)(this["SaveWithoutEncryption"]));
            }
            set {
                this["SaveWithoutEncryption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportUniqueOnly {
            get {
                return ((bool)(this["ExportUniqueOnly"]));
            }
            set {
                this["ExportUniqueOnly"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CellView_ShowEditorNames {
            get {
                return ((bool)(this["CellView_ShowEditorNames"]));
            }
            set {
                this["CellView_ShowEditorNames"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CellView_ShowTypes {
            get {
                return ((bool)(this["CellView_ShowTypes"]));
            }
            set {
                this["CellView_ShowTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowFieldDescriptions {
            get {
                return ((bool)(this["ShowFieldDescriptions"]));
            }
            set {
                this["ShowFieldDescriptions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VerboseCSVExport {
            get {
                return ((bool)(this["VerboseCSVExport"]));
            }
            set {
                this["VerboseCSVExport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int FieldColor_Int_R {
            get {
                return ((int)(this["FieldColor_Int_R"]));
            }
            set {
                this["FieldColor_Int_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int FieldColor_Int_G {
            get {
                return ((int)(this["FieldColor_Int_G"]));
            }
            set {
                this["FieldColor_Int_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int FieldColor_Int_B {
            get {
                return ((int)(this["FieldColor_Int_B"]));
            }
            set {
                this["FieldColor_Int_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int FieldColor_Float_R {
            get {
                return ((int)(this["FieldColor_Float_R"]));
            }
            set {
                this["FieldColor_Float_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int FieldColor_Float_G {
            get {
                return ((int)(this["FieldColor_Float_G"]));
            }
            set {
                this["FieldColor_Float_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int FieldColor_Float_B {
            get {
                return ((int)(this["FieldColor_Float_B"]));
            }
            set {
                this["FieldColor_Float_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int FieldColor_Bool_R {
            get {
                return ((int)(this["FieldColor_Bool_R"]));
            }
            set {
                this["FieldColor_Bool_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int FieldColor_Bool_G {
            get {
                return ((int)(this["FieldColor_Bool_G"]));
            }
            set {
                this["FieldColor_Bool_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("230")]
        public int FieldColor_Bool_B {
            get {
                return ((int)(this["FieldColor_Bool_B"]));
            }
            set {
                this["FieldColor_Bool_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int FieldColor_String_R {
            get {
                return ((int)(this["FieldColor_String_R"]));
            }
            set {
                this["FieldColor_String_R"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int FieldColor_String_G {
            get {
                return ((int)(this["FieldColor_String_G"]));
            }
            set {
                this["FieldColor_String_G"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public int FieldColor_String_B {
            get {
                return ((int)(this["FieldColor_String_B"]));
            }
            set {
                this["FieldColor_String_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEnums {
            get {
                return ((bool)(this["ShowEnums"]));
            }
            set {
                this["ShowEnums"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowEnumValueInName {
            get {
                return ((bool)(this["ShowEnumValueInName"]));
            }
            set {
                this["ShowEnumValueInName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableFieldValidation {
            get {
                return ((bool)(this["EnableFieldValidation"]));
            }
            set {
                this["EnableFieldValidation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableFilterBar {
            get {
                return ((bool)(this["EnableFilterBar"]));
            }
            set {
                this["EnableFilterBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(":")]
        public string Filter_CommandDelimiter {
            get {
                return ((string)(this["Filter_CommandDelimiter"]));
            }
            set {
                this["Filter_CommandDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("~")]
        public string Filter_SectionDelimiter {
            get {
                return ((string)(this["Filter_SectionDelimiter"]));
            }
            set {
                this["Filter_SectionDelimiter"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayBooleanEnumAsCheckbox {
            get {
                return ((bool)(this["DisplayBooleanEnumAsCheckbox"]));
            }
            set {
                this["DisplayBooleanEnumAsCheckbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisableEnumForCustomTypes {
            get {
                return ((bool)(this["DisableEnumForCustomTypes"]));
            }
            set {
                this["DisableEnumForCustomTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NewRow_RepeatCount {
            get {
                return ((int)(this["NewRow_RepeatCount"]));
            }
            set {
                this["NewRow_RepeatCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int NewRow_StepValue {
            get {
                return ((int)(this["NewRow_StepValue"]));
            }
            set {
                this["NewRow_StepValue"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CellView_ShowPadding
        {
            get
            {
                return ((bool)(this["CellView_ShowPadding"]));
            }
            set
            {
                this["CellView_ShowPadding"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CodeExport_CondenseOutpust
        {
            get
            {
                return ((bool)(this["CodeExport_CondenseOutpust"]));
            }
            set
            {
                this["CodeExport_CondenseOutpust"] = value;
            }
        }
    }
}
